import 'package:core/domain/models/exercise.dart';

final List<Exercise> presetExercises = [
  // PECHO
  Exercise(
    id: 'ex_bench_press',
    name: 'Press de Banca',
    muscleGroup: 'Pecho',
    secondaryMuscles: ['Tríceps', 'Hombros'],
    equipment: 'Barra',
    instructions: 'Túmbate en el banco, agarre a la anchura de los hombros, baja la barra al pecho y empuja de vuelta.',
  ),
  Exercise(
    id: 'ex_incline_db_press',
    name: 'Press Inclinado c/M',
    muscleGroup: 'Pecho',
    secondaryMuscles: ['Tríceps', 'Hombros'],
    equipment: 'Mancuernas',
    instructions: 'En banco inclinado a 30-45°, empuja las mancuernas hacia arriba.',
  ),
  Exercise(
    id: 'ex_chest_flyes',
    name: 'Aperturas en Máquina',
    muscleGroup: 'Pecho',
    secondaryMuscles: [],
    equipment: 'Máquina',
    instructions: 'Mantén una ligera flexión en los codos y junta las manos frente a tu pecho.',
  ),
  Exercise(
    id: 'ex_cable_crossover',
    name: 'Cruces en Polea',
    muscleGroup: 'Pecho',
    secondaryMuscles: [],
    equipment: 'Polea',
    instructions: 'Desde polea alta o baja, junta los cables frente a tu cuerpo contrayendo el pecho.',
  ),
  Exercise(
    id: 'ex_peck_deck',
    name: 'Peck Deck',
    muscleGroup: 'Pecho',
    secondaryMuscles: [],
    equipment: 'Máquina',
    instructions: 'Sentado en la máquina, junta los brazos frente al pecho apretando los pectorales.',
  ),
  Exercise(
    id: 'ex_hammer_press',
    name: 'Press Hammer',
    muscleGroup: 'Pecho',
    secondaryMuscles: ['Tríceps', 'Hombros'],
    equipment: 'Máquina',
    instructions: 'Empuja las palancas hacia adelante controlando la fase excéntrica.',
  ),
  Exercise(
    id: 'ex_high_pulley_fly',
    name: 'Fly en Polea Alta',
    muscleGroup: 'Pecho',
    secondaryMuscles: [],
    equipment: 'Polea',
    instructions: 'Desde poleas altas, cruza los cables hacia abajo apuntando a la zona inferior del pecho.',
  ),

  // ESPALDA
  Exercise(
    id: 'ex_pullups',
    name: 'Dominadas',
    muscleGroup: 'Espalda',
    secondaryMuscles: ['Bíceps'],
    equipment: 'Peso corporal',
    instructions: 'Agarre pronado ligeramente más ancho que los hombros. Sube hasta pasar la barbilla por la barra.',
  ),
  Exercise(
    id: 'ex_lat_pulldown',
    name: 'Jalón al Pecho',
    muscleGroup: 'Espalda',
    secondaryMuscles: ['Bíceps'],
    equipment: 'Polea',
    instructions: 'Jala la barra hacia la parte superior del pecho juntando las escápulas.',
  ),
  Exercise(
    id: 'ex_barbell_row',
    name: 'Remo con Barra',
    muscleGroup: 'Espalda',
    secondaryMuscles: ['Bíceps', 'Espalda baja'],
    equipment: 'Barra',
    instructions: 'Torso inclinado a 45°, jala la barra hacia el ombligo.',
  ),
  Exercise(
    id: 'ex_cable_row',
    name: 'Remo en Polea Baja',
    muscleGroup: 'Espalda',
    secondaryMuscles: ['Bíceps'],
    equipment: 'Polea',
    instructions: 'Mantén la espalda recta y jala el agarre hacia tu abdomen.',
  ),
  Exercise(
    id: 'ex_face_pull',
    name: 'Face Pull',
    muscleGroup: 'Espalda',
    secondaryMuscles: ['Hombros posteriores'],
    equipment: 'Polea',
    instructions: 'Jala la cuerda hacia tu cara, separando las manos y rotando los hombros externamente.',
  ),
  Exercise(
    id: 'ex_kelso_shrugs',
    name: 'Kelso Shrugs',
    muscleGroup: 'Espalda',
    secondaryMuscles: ['Trapecios'],
    equipment: 'Mancuernas',
    instructions: 'Apoyado boca abajo en un banco inclinado, retrae las escápulas sin flexionar los codos.',
  ),
  Exercise(
    id: 'ex_machine_unilateral_row',
    name: 'Remo Unilateral Máquina',
    muscleGroup: 'Espalda',
    secondaryMuscles: ['Bíceps'],
    equipment: 'Máquina',
    instructions: 'Tira de la palanca con un solo brazo, concentrándote en el dorsal.',
  ),
  Exercise(
    id: 'ex_t_bar_row',
    name: 'Remo en T',
    muscleGroup: 'Espalda',
    secondaryMuscles: ['Bíceps', 'Espalda baja'],
    equipment: 'Máquina',
    instructions: 'Inclinado sobre la plataforma, tira del agarre en V hacia tu pecho.',
  ),
  Exercise(
    id: 'ex_neutral_pulldown',
    name: 'Jalón Pecho Agarre Neutro',
    muscleGroup: 'Espalda',
    secondaryMuscles: ['Bíceps'],
    equipment: 'Polea',
    instructions: 'Usa el agarre neutro cerrado y baja hacia el pecho enfatizando el dorsal.',
  ),

  // HOMBROS
  Exercise(
    id: 'ex_ohp',
    name: 'Press Militar',
    muscleGroup: 'Hombros',
    secondaryMuscles: ['Tríceps'],
    equipment: 'Barra',
    instructions: 'De pie o sentado, empuja la barra desde las clavículas por encima de la cabeza.',
  ),
  Exercise(
    id: 'ex_db_shoulder_press',
    name: 'Press de Hombros c/M',
    muscleGroup: 'Hombros',
    secondaryMuscles: ['Tríceps'],
    equipment: 'Mancuernas',
    instructions: 'Empuja las mancuernas por encima de la cabeza hasta casi bloquear los codos.',
  ),
  Exercise(
    id: 'ex_lateral_raises',
    name: 'Elevaciones Laterales',
    muscleGroup: 'Hombros',
    secondaryMuscles: [],
    equipment: 'Mancuernas',
    instructions: 'Eleva los brazos hacia los lados hasta la altura de los hombros.',
  ),
  Exercise(
    id: 'ex_reverse_pec_deck',
    name: 'Pájaros en Máquina',
    muscleGroup: 'Hombros',
    secondaryMuscles: ['Espalda'],
    equipment: 'Máquina',
    instructions: 'Empuja hacia atrás usando el deltoide posterior.',
  ),
  Exercise(
    id: 'ex_machine_lateral_raises',
    name: 'Elevaciones Laterales M.',
    muscleGroup: 'Hombros',
    secondaryMuscles: [],
    equipment: 'Máquina',
    instructions: 'Eleva los brazos empujando contra las almohadillas de la máquina.',
  ),
  Exercise(
    id: 'ex_cable_rear_delt',
    name: 'Elevaciones Posteriores P.',
    muscleGroup: 'Hombros',
    secondaryMuscles: ['Espalda'],
    equipment: 'Polea',
    instructions: 'Cruza los cables frente a ti y ábrelos hacia atrás aislando el deltoide posterior.',
  ),

  // BÍCEPS
  Exercise(
    id: 'ex_barbell_curl',
    name: 'Curl con Barra',
    muscleGroup: 'Bíceps',
    secondaryMuscles: [],
    equipment: 'Barra',
    instructions: 'De pie, flexiona los codos subiendo la barra sin balancear el torso.',
  ),
  Exercise(
    id: 'ex_db_curl',
    name: 'Curl Alterno c/M',
    muscleGroup: 'Bíceps',
    secondaryMuscles: [],
    equipment: 'Mancuernas',
    instructions: 'Sube las mancuernas alternando los brazos, supinando la muñeca al subir.',
  ),
  Exercise(
    id: 'ex_hammer_curl',
    name: 'Curl Martillo',
    muscleGroup: 'Bíceps',
    secondaryMuscles: ['Antebrazos'],
    equipment: 'Mancuernas',
    instructions: 'Agarre neutro (palmas enfrentadas), sube las mancuernas hacia los hombros.',
  ),
  Exercise(
    id: 'ex_incline_db_curl',
    name: 'Curl Inclinado 65°',
    muscleGroup: 'Bíceps',
    secondaryMuscles: [],
    equipment: 'Mancuernas',
    instructions: 'En banco a 65 grados, permite que los brazos cuelguen atrás y flexiona los codos.',
  ),
  Exercise(
    id: 'ex_low_pulley_curl',
    name: 'Curl en Polea Baja',
    muscleGroup: 'Bíceps',
    secondaryMuscles: [],
    equipment: 'Polea',
    instructions: 'De pie frente a la polea baja, flexiona los codos manteniendo la tensión constante.',
  ),
  Exercise(
    id: 'ex_unilateral_scott_hammer',
    name: 'Curl Martillo Scott Uni.',
    muscleGroup: 'Bíceps',
    secondaryMuscles: ['Antebrazos'],
    equipment: 'Mancuernas',
    instructions: 'Apoya el brazo en el banco Scott y realiza el curl con agarre neutro.',
  ),

  // TRÍCEPS
  Exercise(
    id: 'ex_tricep_pushdown',
    name: 'Extensiones de Tríceps',
    muscleGroup: 'Tríceps',
    secondaryMuscles: [],
    equipment: 'Polea',
    instructions: 'Empuja el agarre hacia abajo extendiendo los codos por completo.',
  ),
  Exercise(
    id: 'ex_overhead_tricep',
    name: 'Extensión Sobre la Cabeza',
    muscleGroup: 'Tríceps',
    secondaryMuscles: [],
    equipment: 'Mancuernas',
    instructions: 'Detrás del cuello, extiende los brazos hacia arriba aislando el tríceps.',
  ),
  Exercise(
    id: 'ex_dips',
    name: 'Fondos en Paralelas',
    muscleGroup: 'Tríceps',
    secondaryMuscles: ['Pecho', 'Hombros'],
    equipment: 'Peso corporal',
    instructions: 'Baja tu cuerpo flexionando los codos y empuja hasta volver a la posición inicial.',
  ),
  Exercise(
    id: 'ex_v_bar_pushdown',
    name: 'Extensiones con Barra V',
    muscleGroup: 'Tríceps',
    secondaryMuscles: [],
    equipment: 'Polea',
    instructions: 'Usa el agarre en V y extiende los codos por completo hacia abajo.',
  ),
  Exercise(
    id: 'ex_french_press',
    name: 'Press Francés',
    muscleGroup: 'Tríceps',
    secondaryMuscles: [],
    equipment: 'Barra',
    instructions: 'Tumbado, baja la barra Z hacia la frente o por detrás de la cabeza y extiende los codos.',
  ),
  Exercise(
    id: 'ex_machine_dips',
    name: 'Fondos en Máquina',
    muscleGroup: 'Tríceps',
    secondaryMuscles: ['Pecho', 'Hombros'],
    equipment: 'Máquina',
    instructions: 'Empuja las palancas hacia abajo manteniendo el torso erguido para aislar el tríceps.',
  ),

  // CUÁDRICEPS Y PIERNA
  Exercise(
    id: 'ex_squat',
    name: 'Sentadilla Libre',
    muscleGroup: 'Cuádriceps',
    secondaryMuscles: ['Glúteos', 'Isquios', 'Core'],
    equipment: 'Barra',
    instructions: 'Barra en la espalda alta, baja hasta romper el paralelo y sube con explosividad.',
  ),
  Exercise(
    id: 'ex_leg_press',
    name: 'Prensa Inclinada',
    muscleGroup: 'Cuádriceps',
    secondaryMuscles: ['Glúteos'],
    equipment: 'Máquina',
    instructions: 'Empuja la plataforma controladamente evitando bloquear las rodillas de golpe.',
  ),
  Exercise(
    id: 'ex_leg_extension',
    name: 'Extensiones de Cuádriceps',
    muscleGroup: 'Cuádriceps',
    secondaryMuscles: [],
    equipment: 'Máquina',
    instructions: 'Extiende las piernas por completo y aguanta 1 segundo en la máxima contracción.',
  ),
  Exercise(
    id: 'ex_bulgarian_split_squat',
    name: 'Sentadilla Búlgara',
    muscleGroup: 'Cuádriceps',
    secondaryMuscles: ['Glúteos'],
    equipment: 'Mancuernas',
    instructions: 'Un pie apoyado en un banco atrás, baja hasta que la rodilla trasera roce el suelo.',
  ),
  Exercise(
    id: 'ex_pendulum_squat',
    name: 'Sentadilla Pendular',
    muscleGroup: 'Cuádriceps',
    secondaryMuscles: ['Glúteos'],
    equipment: 'Máquina',
    instructions: 'Baja profundamente en la máquina pendular enfocándote en los cuádriceps.',
  ),
  Exercise(
    id: 'ex_adductor',
    name: 'Aductor en Máquina',
    muscleGroup: 'Piernas',
    secondaryMuscles: [],
    equipment: 'Máquina',
    instructions: 'Junta las piernas venciendo la resistencia de la máquina.',
  ),

  // ISQUIOS Y GLÚTEOS
  Exercise(
    id: 'ex_rdl',
    name: 'Peso Muerto Rumano',
    muscleGroup: 'Isquios',
    secondaryMuscles: ['Glúteos', 'Espalda baja'],
    equipment: 'Barra',
    instructions: 'Desplaza la cadera hacia atrás manteniendo las piernas casi rectas hasta sentir estiramiento.',
  ),
  Exercise(
    id: 'ex_leg_curl',
    name: 'Curl Femoral',
    muscleGroup: 'Isquios',
    secondaryMuscles: [],
    equipment: 'Máquina',
    instructions: 'Genérico: flexiona las rodillas contrayendo los isquiotibiales.',
  ),
  Exercise(
    id: 'ex_lying_leg_curl',
    name: 'Curl Femoral Acostado',
    muscleGroup: 'Isquios',
    secondaryMuscles: [],
    equipment: 'Máquina',
    instructions: 'Acostado boca abajo, flexiona las rodillas llevando el pad hacia los glúteos.',
  ),
  Exercise(
    id: 'ex_seated_leg_curl',
    name: 'Curl Femoral Sentado',
    muscleGroup: 'Isquios',
    secondaryMuscles: [],
    equipment: 'Máquina',
    instructions: 'Sentado, flexiona las rodillas tirando del pad hacia abajo.',
  ),
  Exercise(
    id: 'ex_standing_leg_curl',
    name: 'Curl Femoral Parado',
    muscleGroup: 'Isquios',
    secondaryMuscles: [],
    equipment: 'Máquina',
    instructions: 'De pie, flexiona una rodilla a la vez llevando el talón hacia el glúteo.',
  ),
  Exercise(
    id: 'ex_hip_thrust',
    name: 'Hip Thrust',
    muscleGroup: 'Glúteos',
    secondaryMuscles: ['Isquios'],
    equipment: 'Barra',
    instructions: 'Espalda alta en un banco, empuja la cadera hacia arriba contrayendo fuertemente los glúteos.',
  ),
  Exercise(
    id: 'ex_abductor',
    name: 'Abductor en Máquina',
    muscleGroup: 'Glúteos',
    secondaryMuscles: [],
    equipment: 'Máquina',
    instructions: 'Separa las piernas venciendo la resistencia para trabajar el glúteo medio.',
  ),

  // PANTORRILLAS Y ABDOMEN
  Exercise(
    id: 'ex_calf_raise',
    name: 'Elevación de Gemelos',
    muscleGroup: 'Pantorrillas',
    secondaryMuscles: [],
    equipment: 'Máquina',
    instructions: 'Eleva los talones al máximo y baja lentamente hasta sentir el estiramiento.',
  ),
  Exercise(
    id: 'ex_crunch',
    name: 'Crunches',
    muscleGroup: 'Abdomen',
    secondaryMuscles: [],
    equipment: 'Peso corporal',
    instructions: 'Eleva los hombros del suelo contrayendo el abdomen.',
  ),
];
