-- Roadmap 4.0 / Fase 1
-- Server-authoritative Coach Pro entitlements, limits and write guards.
-- This migration is intentionally validated only in isolated CI until an
-- explicit remote deployment authorization is given.

create table if not exists public.stk_subscription_entitlements (
  user_id uuid not null references auth.users(id) on delete cascade,
  product text not null,
  status text not null,
  tier text not null default 'standard',
  client_limit integer not null default 1,
  starts_at timestamptz not null default now(),
  current_period_end timestamptz,
  grace_until timestamptz,
  source text not null default 'manual',
  updated_at timestamptz not null default now(),
  primary key (user_id, product),
  constraint stk_subscription_entitlements_product
    check (product in ('coach_pro')),
  constraint stk_subscription_entitlements_status
    check (status in ('trial','active','grace','past_due','canceled','expired')),
  constraint stk_subscription_entitlements_tier
    check (
      char_length(tier) between 1 and 64
      and tier ~ '^[a-z0-9][a-z0-9_-]*$'
    ),
  constraint stk_subscription_entitlements_client_limit
    check (client_limit between 1 and 1000),
  constraint stk_subscription_entitlements_source
    check (char_length(source) between 1 and 64)
);

create table if not exists public.stk_entitlement_audit_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product text not null,
  status text not null,
  tier text not null,
  client_limit integer not null,
  source text not null,
  event_key text unique,
  created_at timestamptz not null default now(),
  constraint stk_entitlement_audit_product
    check (product in ('coach_pro')),
  constraint stk_entitlement_audit_status
    check (status in ('trial','active','grace','past_due','canceled','expired')),
  constraint stk_entitlement_audit_event_key
    check (event_key is null or char_length(event_key) between 1 and 200)
);

create index if not exists stk_subscription_entitlements_product_status_idx
  on public.stk_subscription_entitlements (product, status, updated_at desc);

create index if not exists stk_entitlement_audit_user_created_idx
  on public.stk_entitlement_audit_events (user_id, created_at desc);

alter table public.stk_subscription_entitlements enable row level security;
alter table public.stk_entitlement_audit_events enable row level security;

revoke all on public.stk_subscription_entitlements from anon, authenticated;
revoke all on public.stk_entitlement_audit_events from anon, authenticated;

-- Deliberately no authenticated table policies. Clients read only a redacted
-- self snapshot through stk_get_own_subscription_entitlement(). Billing/admin
-- writes are server-only.

create or replace function public.stk_entitlement_active_for_user(
  p_user_id uuid,
  p_product text
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
      from public.stk_subscription_entitlements as entitlement
     where entitlement.user_id = p_user_id
       and entitlement.product = p_product
       and entitlement.starts_at <= now()
       and (
         (
           entitlement.status in ('trial','active')
           and (
             entitlement.current_period_end is null
             or entitlement.current_period_end > now()
           )
         )
         or (
           entitlement.status = 'grace'
           and entitlement.grace_until is not null
           and entitlement.grace_until > now()
         )
       )
  );
$$;

revoke all on function public.stk_entitlement_active_for_user(uuid, text)
  from public, anon, authenticated;

create or replace function public.stk_coach_pro_client_limit_for_user(
  p_user_id uuid
)
returns integer
language sql
stable
security definer
set search_path = ''
as $$
  select case
    when public.stk_entitlement_active_for_user(p_user_id, 'coach_pro')
      then coalesce(
        (
          select entitlement.client_limit
            from public.stk_subscription_entitlements as entitlement
           where entitlement.user_id = p_user_id
             and entitlement.product = 'coach_pro'
           limit 1
        ),
        0
      )
    else 0
  end;
$$;

revoke all on function public.stk_coach_pro_client_limit_for_user(uuid)
  from public, anon, authenticated;

create or replace function public.stk_get_own_subscription_entitlement(
  p_product text default 'coach_pro'
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_entitlement public.stk_subscription_entitlements%rowtype;
  v_active_clients integer := 0;
  v_access_active boolean := false;
begin
  if v_user_id is null
     or coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) then
    raise exception 'Permanent authenticated account required';
  end if;

  if p_product <> 'coach_pro' then
    raise exception 'Unsupported subscription product';
  end if;

  select *
    into v_entitlement
    from public.stk_subscription_entitlements
   where user_id = v_user_id
     and product = p_product
   limit 1;

  if not found then
    return pg_catalog.jsonb_build_object(
      'exists', false,
      'product', p_product,
      'access_active', false,
      'client_limit', 0,
      'active_client_count', 0
    );
  end if;

  v_access_active :=
    public.stk_entitlement_active_for_user(v_user_id, p_product);

  select count(*)::integer
    into v_active_clients
    from public.stk_coach_client_relationships
   where coach_user_id = v_user_id
     and status = 'active';

  return pg_catalog.jsonb_build_object(
    'exists', true,
    'product', v_entitlement.product,
    'status', v_entitlement.status,
    'tier', v_entitlement.tier,
    'client_limit', v_entitlement.client_limit,
    'active_client_count', v_active_clients,
    'starts_at', v_entitlement.starts_at,
    'current_period_end', v_entitlement.current_period_end,
    'grace_until', v_entitlement.grace_until,
    'access_active', v_access_active
  );
end;
$$;

revoke all on function public.stk_get_own_subscription_entitlement(text)
  from public, anon;
grant execute on function public.stk_get_own_subscription_entitlement(text)
  to authenticated;

create or replace function public.stk_set_subscription_entitlement(
  p_user_id uuid,
  p_product text,
  p_status text,
  p_tier text,
  p_client_limit integer,
  p_starts_at timestamptz default now(),
  p_current_period_end timestamptz default null,
  p_grace_until timestamptz default null,
  p_source text default 'backend',
  p_event_key text default null
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_event_id bigint;
begin
  if p_product <> 'coach_pro' then
    raise exception 'Unsupported subscription product';
  end if;
  if p_status not in ('trial','active','grace','past_due','canceled','expired') then
    raise exception 'Unsupported entitlement status';
  end if;
  if p_client_limit < 1 or p_client_limit > 1000 then
    raise exception 'Client limit out of range';
  end if;
  if char_length(btrim(coalesce(p_tier, ''))) < 1
     or char_length(p_tier) > 64
     or p_tier !~ '^[a-z0-9][a-z0-9_-]*$' then
    raise exception 'Invalid entitlement tier';
  end if;
  if char_length(btrim(coalesce(p_source, ''))) < 1
     or char_length(p_source) > 64 then
    raise exception 'Invalid entitlement source';
  end if;
  if p_event_key is not null
     and (char_length(p_event_key) < 1 or char_length(p_event_key) > 200) then
    raise exception 'Invalid entitlement event key';
  end if;

  if p_event_key is not null then
    insert into public.stk_entitlement_audit_events (
      user_id,
      product,
      status,
      tier,
      client_limit,
      source,
      event_key
    )
    values (
      p_user_id,
      p_product,
      p_status,
      p_tier,
      p_client_limit,
      p_source,
      p_event_key
    )
    on conflict (event_key) do nothing
    returning id into v_event_id;

    if v_event_id is null then
      return false;
    end if;
  end if;

  insert into public.stk_subscription_entitlements (
    user_id,
    product,
    status,
    tier,
    client_limit,
    starts_at,
    current_period_end,
    grace_until,
    source,
    updated_at
  )
  values (
    p_user_id,
    p_product,
    p_status,
    p_tier,
    p_client_limit,
    coalesce(p_starts_at, now()),
    p_current_period_end,
    p_grace_until,
    p_source,
    now()
  )
  on conflict (user_id, product) do update
    set status = excluded.status,
        tier = excluded.tier,
        client_limit = excluded.client_limit,
        starts_at = excluded.starts_at,
        current_period_end = excluded.current_period_end,
        grace_until = excluded.grace_until,
        source = excluded.source,
        updated_at = now();

  if p_event_key is null then
    insert into public.stk_entitlement_audit_events (
      user_id,
      product,
      status,
      tier,
      client_limit,
      source
    )
    values (
      p_user_id,
      p_product,
      p_status,
      p_tier,
      p_client_limit,
      p_source
    );
  end if;

  return true;
end;
$$;

revoke all on function public.stk_set_subscription_entitlement(
  uuid, text, text, text, integer, timestamptz, timestamptz, timestamptz, text, text
) from public, anon, authenticated;
grant execute on function public.stk_set_subscription_entitlement(
  uuid, text, text, text, integer, timestamptz, timestamptz, timestamptz, text, text
) to service_role;

create or replace function public.stk_assert_coach_pro_access(
  p_coach_user_id uuid
)
returns void
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.stk_entitlement_active_for_user(
    p_coach_user_id,
    'coach_pro'
  ) then
    raise exception 'Coach Pro entitlement required';
  end if;
end;
$$;

revoke all on function public.stk_assert_coach_pro_access(uuid)
  from public, anon, authenticated;

create or replace function public.stk_assert_coach_pro_client_capacity(
  p_coach_user_id uuid,
  p_exclude_relationship_id uuid default null
)
returns void
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_limit integer;
  v_active integer;
begin
  perform public.stk_assert_coach_pro_access(p_coach_user_id);

  v_limit := public.stk_coach_pro_client_limit_for_user(p_coach_user_id);

  select count(*)::integer
    into v_active
    from public.stk_coach_client_relationships
   where coach_user_id = p_coach_user_id
     and status = 'active'
     and (
       p_exclude_relationship_id is null
       or id <> p_exclude_relationship_id
     );

  if v_active >= v_limit then
    raise exception 'Coach Pro client limit reached';
  end if;
end;
$$;

revoke all on function public.stk_assert_coach_pro_client_capacity(uuid, uuid)
  from public, anon, authenticated;

create or replace function public.stk_enforce_coach_pro_invitation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is not null then
    perform public.stk_assert_coach_pro_access(new.coach_user_id);
    perform public.stk_assert_coach_pro_client_capacity(new.coach_user_id);
  end if;
  return new;
end;
$$;

create or replace function public.stk_enforce_coach_pro_relationship_activation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null or new.status <> 'active' then
    return new;
  end if;

  if tg_op = 'INSERT' then
    perform public.stk_assert_coach_pro_client_capacity(
      new.coach_user_id,
      new.id
    );
  elsif old.status is distinct from 'active' then
    perform public.stk_assert_coach_pro_client_capacity(
      new.coach_user_id,
      new.id
    );
  end if;

  return new;
end;
$$;

create or replace function public.stk_enforce_coach_pro_owned_write()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is not null
     and auth.uid() = new.coach_user_id then
    perform public.stk_assert_coach_pro_access(new.coach_user_id);
  end if;
  return new;
end;
$$;

create or replace function public.stk_enforce_coach_pro_task_comment()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_coach_user_id uuid;
begin
  select task.coach_user_id
    into v_coach_user_id
    from public.stk_coach_tasks as task
   where task.id = new.task_id;

  if auth.uid() is not null
     and auth.uid() = v_coach_user_id then
    perform public.stk_assert_coach_pro_access(v_coach_user_id);
  end if;
  return new;
end;
$$;

create or replace function public.stk_enforce_coach_pro_checkin_comment()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_coach_user_id uuid;
begin
  select checkin.coach_user_id
    into v_coach_user_id
    from public.stk_coach_checkins as checkin
   where checkin.id = new.checkin_id;

  if auth.uid() is not null
     and auth.uid() = v_coach_user_id then
    perform public.stk_assert_coach_pro_access(v_coach_user_id);
  end if;
  return new;
end;
$$;

revoke all on function public.stk_enforce_coach_pro_invitation()
  from public, anon, authenticated;
revoke all on function public.stk_enforce_coach_pro_relationship_activation()
  from public, anon, authenticated;
revoke all on function public.stk_enforce_coach_pro_owned_write()
  from public, anon, authenticated;
revoke all on function public.stk_enforce_coach_pro_task_comment()
  from public, anon, authenticated;
revoke all on function public.stk_enforce_coach_pro_checkin_comment()
  from public, anon, authenticated;

drop trigger if exists stk_coach_pro_invitation_guard
  on public.stk_coach_invitations;
create trigger stk_coach_pro_invitation_guard
before insert on public.stk_coach_invitations
for each row execute function public.stk_enforce_coach_pro_invitation();

drop trigger if exists stk_coach_pro_relationship_activation_guard
  on public.stk_coach_client_relationships;
create trigger stk_coach_pro_relationship_activation_guard
before insert or update of status on public.stk_coach_client_relationships
for each row execute function public.stk_enforce_coach_pro_relationship_activation();

drop trigger if exists stk_coach_pro_program_write_guard
  on public.stk_assigned_programs;
create trigger stk_coach_pro_program_write_guard
before insert or update on public.stk_assigned_programs
for each row execute function public.stk_enforce_coach_pro_owned_write();

drop trigger if exists stk_coach_pro_task_write_guard
  on public.stk_coach_tasks;
create trigger stk_coach_pro_task_write_guard
before insert or update on public.stk_coach_tasks
for each row execute function public.stk_enforce_coach_pro_owned_write();

drop trigger if exists stk_coach_pro_nutrition_write_guard
  on public.stk_nutrition_guidance_plans;
create trigger stk_coach_pro_nutrition_write_guard
before insert or update on public.stk_nutrition_guidance_plans
for each row execute function public.stk_enforce_coach_pro_owned_write();

drop trigger if exists stk_coach_pro_task_comment_guard
  on public.stk_coach_task_comments;
create trigger stk_coach_pro_task_comment_guard
before insert on public.stk_coach_task_comments
for each row execute function public.stk_enforce_coach_pro_task_comment();

drop trigger if exists stk_coach_pro_checkin_comment_guard
  on public.stk_coach_checkin_comments;
create trigger stk_coach_pro_checkin_comment_guard
before insert on public.stk_coach_checkin_comments
for each row execute function public.stk_enforce_coach_pro_checkin_comment();

comment on table public.stk_subscription_entitlements is
  'Server-authoritative commercial entitlements. Never writable or directly readable by authenticated clients.';
comment on function public.stk_get_own_subscription_entitlement(text) is
  'Returns a redacted self entitlement snapshot for UX only; backend guards remain authoritative.';
comment on table public.stk_user_capabilities is
  'Functional roles such as athlete/coach. Capabilities are not paid licenses and never replace Coach Pro entitlement checks.';
